# Configure a default setup of Home Assistant (frontend, api, etc)
#
# examples: https://www.home-assistant.io/examples/#example-configurationyaml
#
default_config:

logger:
  default: debug
  # logs:
  #   custom_components.hacs: debug
  #   hacs: debug
  #   queueman: debug
  #   AIOGitHubAPI: debug

homeassistant:
  internal_url: "https://hass.i.apealive.net"
  external_url: "https://hass.apealive.net"

#frontend:
  #themes:
    #!include_dir_merge_named themes

automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
group:
  !include groups.yaml
script:
  !include scripts.yaml
scene:
  !include scenes.yaml
# integrations:
#   !include integrations.yaml


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'cs'
    cache: true
    time_memory: 300
    base_url: https://hass.apealive.net #:8123

# A request from a reverse proxy was received from 10.1.3.206, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/16
    - 172.32.0.0/16
    - 172.31.0.0/16
    - 10.1.0.0/16
    - ::1


calendar:
- platform: ics
  calendars:
      - name: Rodina
        url: "https://calendar.google.com/calendar/embed?src=family12747428898484624446%40group.calendar.google.com&ctz=Europe%2FPrague"
        includeAllDay: true

# lovelace:
#   mode: yaml
#   resources: !include /config/lovelace/resources.yaml
#   dashboards:
#     # lovelace-system:
#     #   mode: yaml
#     #   filename: ui-system.yaml
#     #   title: "System"
#     #   icon: mdi:view-dashboard
#     #   show_in_sidebar: true
#     #   require_admin: false
#     lovelace-wallpanel:
#       mode: yaml
#       filename: ui-wallpanel.yaml
#       title: "Wall Panel"
#       icon: mdi:view-dashboard
#       show_in_sidebar: true
#       require_admin: false


# https://www.home-assistant.io/integrations/modbus/
#
modbus:
# TC Acond
# https://github.com/JH-Soft-Technology/acond-heat-card
# https://github.com/zdychacek/homebridge-acond-therm
- name: "hub"
  type: tcp
  host: "{{ secrets.vip_acond }}"
  port: 502
# SPA
- name: "usspa"
  type: tcp
  host: "{{ secrets.vip_usspa }}"
  port: 502
  sensors:
  - name: Water_Temp_Act_Hi
    #id: spa_water_temp_act_hi
    scan_interval: 60
    address: 0x350
    data_type: float32
    #unit_of_measurement: "°C"
#  - name: Water_Temp_Act_Lo
#    #id: spa_water_temp_act_lo
#   scan_interval: 60
#    address: 351
#    data_type: float32
#    #temperature_unit: C
  - name: Pump1_Slow
    #id: spa_pump1_slow
    scan_interval: 60
    address: 0x407
    data_type: int16
  - name: Pump1_Fast
    #id: spa_pump1_fast
    scan_interval: 60
    address: 0x409
    data_type: int16
  - name: Pump2
    #id: spa_pump2
    scan_interval: 60
    address: 0x40B
    data_type: int16
  - name: Pump3
    #id: spa_pump3
    scan_interval: 60
    address: 0x40D
    data_type: int16
  - name: Light1
    #id: spa_light1
    scan_interval: 60
    address: 0x413
    data_type: int16
#  - name: Light2
#    #id: spa_light2
#    scan_interval: 60
#    address: 415
#    data_type: int16
#  - name: Kryt
#    #id: spa_cover_status
#    scan_interval: 60
#    address: 36D 
#    slave: 0
#    data_type: int32
  #binary_sensors:
  #  - name: "binary_sensor1"
  #    address: 100
  #    scan_interval: 20
  #    slave: 1
  #  - name: "binary_sensor2"
  #    address: 110
  #    device_class: door
  #    input_type: discrete_input

# https://www.home-assistant.io/integrations/homekit/
#homekit:
#- filter:
#    include_domains:
#    - light
#    - media_player
#    include_entity_globs:
#    - binary_sensor.*_occupancy
#    #include_entities:
#    #- binary_sensor.living_room_motion
#  entity_config:
#    media_player.living_room:
#      feature_list:
#        - feature: on_off
#        - feature: play_pause
#        - feature: play_stop
#        - feature: toggle_mute
