fullnameOverride: adguard
image:
   repository: adguard/adguardhome
   tag: v0.107.26
controller:
  replicas: 1

env:
  TZ: Europe/Prague

persistence:
  config: 
    # NOTE: if enabled pod/init-container wont update AdGuard config if it exist already
    enabled: true
    # existingClaim:
    # size: 1Gi
    mountPath: /opt/adguardhome/conf
    storageClass: longhorn-static
    accessMode: ReadWriteOnce
  data:
    enabled: false
    mountPath: /opt/adguardhome/work
    storageClass: longhorn-static
    accessMode: ReadWriteOnce

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: false



service:
  main:
    ports:
      http:
        port: 3000
  dns-tcp:
    enabled: false
    type: LoadBalancer
    loadBalancerIP: {{ secrets.vip_adgrd_tcp }}
    ports:
      dns-tcp:
        port: 53
    #    protocol: TCP
    #    targetPort: 53
    #externalTrafficPolicy: Local
    externalIPs:
    - 172.31.1.52
    - 172.31.5.52
  dns-udp:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: {{ secrets.vip_adgrd }}
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
    externalTrafficPolicy: Local
    annotations: # NOT VERIFIED
      metallb.universe.tf/allow-shared-ip: adguard-dns-tcp
    externalIPs:
    - 172.31.1.53
    - 172.31.5.53


ingress:
   main:
     enabled: true
     ingressClassName: "traefik"
     annotations:
      #external-dns/is-public: "false"
      #external-dns.alpha.kubernetes.io/target: "ipv4.apealive.net"
      #kubernetes.io/ingress.class: "traefik"
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
       traefik.ingress.kubernetes.io/router.tls: "true"
       hajimari.io/enable: "true"
       hajimari.io/icon: shield-check
       hajimari.io/group: network
       hajimari.io/appName: adguard
     hosts:
     - host: adguard.apealive.net
       paths:
       - path: /
         pathType: Prefix
     tls:
     - hosts:
       - adguard.apealive.net

resources:
  requests:
    memory: 200Mi
    cpu: 200m    
  limits:
    memory: 2000Mi
    cpu: 1

# FIXME, this needs to be thin-merged with  upstream
# however kustomize lacks proper support for it
#https://github.com/k8s-at-home/charts/blob/master/charts/stable/adguard-home/values.yaml
config: |-
  bind_host: 0.0.0.0
  bind_port: 3000
  beta_bind_port: 0
  users: []
  auth_attempts: 5
  block_auth_min: 15
  http_proxy: ""
  language: en
  rlimit_nofile: 0
  debug_pprof: false
  web_session_ttl: 720
  dns:
    bind_hosts:
    - 0.0.0.0
    port: 53
    statistics_interval: 1
    querylog_enabled: true
    querylog_file_enabled: true
    querylog_interval: 90
    querylog_size_memory: 1000
    anonymize_client_ip: false
    protection_enabled: true
    blocking_mode: default
    blocking_ipv4: ""
    blocking_ipv6: ""
    blocked_response_ttl: 10
    parental_block_host: family-block.dns.adguard.com
    safebrowsing_block_host: standard-block.dns.adguard.com
    ratelimit: 0
    ratelimit_whitelist: []
    refuse_any: true
    upstream_dns:
    - https://dns10.quad9.net/dns-query
    upstream_dns_file: ""
    bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
    all_servers: false
    fastest_addr: false
    allowed_clients: []
    disallowed_clients: []
    blocked_hosts: []
    cache_size: 4194304
    cache_ttl_min: 0
    cache_ttl_max: 0
    bogus_nxdomain: []
    aaaa_disabled: false
    enable_dnssec: false
    edns_client_subnet: false
    max_goroutines: 300
    ipset: []
    filtering_enabled: true
    filters_update_interval: 24
    parental_enabled: false
    safesearch_enabled: false
    safebrowsing_enabled: false
    safebrowsing_cache_size: 1048576
    safesearch_cache_size: 1048576
    parental_cache_size: 1048576
    cache_time: 30
    ##
    rewrites:
    - domain: 'git.apealive.net'
      answer: {{ secrets.vip_gitea }}
    # - domain: 'hass.apealive.net'
    #   answer: {{ secrets.vip_traef }}
    # - domain: '*.apealive.net'
    #   answer: {{ secrets.vip_traef }}
    ##
    blocked_services: []
    local_domain_name: lan
    resolve_clients: true
    local_ptr_upstreams: []
  tls:
    enabled: false
    server_name: ""
    force_https: false
    port_https: 443
    port_dns_over_tls: 853
    port_dns_over_quic: 784
    port_dnscrypt: 0
    dnscrypt_config_file: ""
    allow_unencrypted_doh: false
    strict_sni_check: false
    certificate_chain: ""
    private_key: ""
    certificate_path: ""
    private_key_path: ""
  filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://adaway.org/hosts.txt
    name: AdAway
    id: 2
  - enabled: false
    url: https://www.malwaredomainlist.com/hostslist/hosts.txt
    name: MalwareDomainList.com Hosts List
    id: 4
  whitelist_filters: []
  user_rules: []
  dhcp:
    enabled: false
    interface_name: ""
    dhcpv4:
      gateway_ip: ""
      subnet_mask: ""
      range_start: ""
      range_end: ""
      lease_duration: 86400
      icmp_timeout_msec: 1000
      options: []
    dhcpv6:
      range_start: ""
      lease_duration: 86400
      ra_slaac_only: false
      ra_allow_slaac: false
  clients: []
  log_compress: false
  log_localtime: false
  log_max_backups: 0
  log_max_size: 100
  log_max_age: 3
  log_file: ""
  verbose: false
  schema_version: 10


