apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  sourceType: Helm
  project: default
  destination:
    namespace: sys
    server: https://kubernetes.default.svc
  source:
    path: home/traefik
    repoURL: git@github.com:epcim/gitops-fleet.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: false
    syncOptions:
    - CreateNamespace=true
