# https://kluctl.io/docs/kluctl/reference/kluctl-project/
discriminator: kluctl-{{target.name | slugify }}{% if args.manual %}-manual{% endif %}

args:
- name: env
  default: kwok
- name: bootstrap     # indicates first time start for the component (if required)
  default: false
- name: manual        # will not be executed by controller reconciliation
  default: false
- name: controller    # indicates deployment through kluctl controller
  default: false
#
# library/stacks
# and their args configuration
- name: stacks
  default: {}

# NOTE: Targets points to k8s and deploy deployment.yml &./cluster-* 
# NOTE: Cluster folder is configuration wrapper for library or stack
# NOTE: Kwok, Kind  cluster is only used for testing and development
# NOTE: target.context: PATH to file or KUBECONFIG env value is used

targets:

# PRODUCTION TARGETS
- name: cluster-example
  ## context: .kube/config # or $KUBECONFIG exported on .envrc.local
  args:
    env: eample
    flavor: "test"
    domain: example.net
    ingress: traefik
    stacks:
      cicd: true
      monitoring: false


# TEST TARGETS
- name: kwok # kwokctl --name $ENV create cluster
  # context: FROM KUBECONFIG ENV, ie: KUBECONFIG=$HOME/.kwok/clusters/$ENV/kubeconfig.yaml 
  args:
    env: test
    bootstrap: true
    
- name: kind # kind create cluster
  context: kind-kind
  args:
    env: test
    bootstrap: true
