# https://kluctl.io/docs/kluctl/reference/kluctl-project/

#discriminator: "kluctl-{{ target.name }}"

targets:
- name: base
  # context: # SOURCED FROM ENV. KUBECONFIG
  args:
    environment: prod

- name: apealive
  args:
    environment: prod

# for testing, use `kind create cluster`
- name: test
  context: kind-kind
  args:
    bootstrap: true
- name: virtual
  context: kwok
  args:
    bootstrap: true


args:
- name: oneshot # to install single service only
  default: ""
- name: bootstrap
  default: false
- name: oneshot # to install single service only
  default: ""
- name: platform
  default: microk8s

