# https://kluctl.io/docs/kluctl/reference/kluctl-project/

# NOTE: Some targets are deployment `layers` of for the same cluster
# NOTE: Kwok, Kind  cluster is only used for testing and development
targets:
- name: base
  #context: PATH or from KUBECONFIG env
  args:
    bootstrap: true
    envtype: primary

- name: apealive
  #context: PATH or from KUBECONFIG env
  args:
    envtype: primary

# for testing, use `kwokctl --name $ENV create cluster`
- name: kwok
  #context: FROM KUBECONFIG ENV, ie: KUBECONFIG=$HOME/.kwok/clusters/$ENV/kubeconfig.yaml 
  args:
    bootstrap: true
    cluster_name: lab1
# for testing, use `kind create cluster`
- name: test
  context: kind-kind

discriminator: "kluctl-{{ target.name }}"

args:
- name: bootstrap
  default: false
- name: env
  default: staging
- name: envtype
  default: generic
- name: platform
  default: microk8s
- name: environment
  default: kluctl



# DEPRECATED
- name: oneshot # to install single service only
  default: ""

