# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/
# vim: textwidth=120:nowrap ft=jinja syntax=case

vars:
  - file: cluster-{{args.env}}/vars-env.yml
  - file: cluster-{{args.env}}/vars-sec.yml
    sensitive: true
  - file: cluster-{{args.env}}/vars.yml

deployments:
  - include: ./library/stack/cluster-base
  - include: cluster-{{args.env}}

  {%- for stack in args.stacks %}
  - when: args.stacks.{{ stack }}
    include: ./library/stack/{{ stack }}
    vars:
     - file: ./library/stack/{{ stack }}/vars.yml
       noOverride: true
       ignoreMissing: true
    tags: [{{ stack }}]
  {%- endfor %}

ignoreForDiff:
  - group: cicd1
    fieldPathRegex: metadata.labels.(kluctl|argo).*
  - group: webhoooks1
    fieldPathRegex: spec.conversion.webhook.*

commonLabels:
  examples.kluctl.io/deployment-target: "{{ target.name }}"

# TODO: 
# 1. try different order cluster-base vs. cluser-ENV
# 2. to get defualts (but from cluster-home)
