# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/
# noOverride: true
# ignoreMissing: true
# when: some.var == "value"

vars:
# implicit
  - file: service/context.yml  # NOTE: in-evaluation
# overrides
  - file: targets/{{ target.name }}/secrets.yml
  - file: targets/{{ target.name }}/context.yml
# inline
  - values:
      bootstrap: true
      #root: ../.. # rel. path to project root (for specified deployments)

deployments:
  - path: compose              # NOTE: in-evaluation
    onlyRender: true
  #- include: targets/base
  #- include: targets/monitoring
  - include: targets/{{ target.name }}


#commonLabels:
  #examples.kluctl.io/environment: "{{ args.environment }}"

# ignoreForDiff:
# - group: apps
#   kind: Deployment
#   namespace: my-namespace
#   name: my-deployment
#   fieldPath: spec.replicas
