# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/

vars:
  - file: context-model.yml
  # inline
  - values:
      bootstrap: false

deployments:
## WORKAROUND to append dependencies to temp. build dir
  - path: ./compose
    onlyRender: true
# ------------------
  - include: cluster

# commonLabels:
#  examples.kluctl.io/environment: "{{ args.environment }}"

ignoreForDiff:
  - group: cicd-1
    fieldPathRegex: metadata.labels.kluctl.*
  - group: cicd-2
    fieldPathRegex: metadata.labels.argo.*

# ignoreForDiff:
# - group: global
#   fieldPath: metadata.labels
# - group: apps
#   kind: Deployment
#   namespace: my-namespace
#   name: my-deployment
#   fieldPath: spec.replicas
#deployments:
# noOverride: true
# ignoreMissing: true
# when: some.var == "value"
# alwaysDeploy: true
