
fullnameOverride: minio-mon

# https://artifacthub.io/packages/helm/bitnami/minio
mode: standalone
auth:
  rootUser:	admin
  rootPassword: {{ secrets.minio_mon.root.password }}

defaultBuckets: "thanos"

service:
  type: LoadBalancer
  #clusterIP:
  #externalTrafficPolicy: Cluster # source ip preservation

# provisioning:
  # users:
  # buckets:
  # groups:

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  requests:
    memory: 1Gi

metrics:
  serviceMonitor:
    enabled: true
