# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/
---

deployments: []
#  - path: longhorn
# FIXME, this is temp. I will switch to include/exclude Tags
{% for s in services %}
  - path: {{ root }}/service/{{ s }}
{% endfor %}


# Example
# deployemnts:
# - path: dugtrio
#   barrier: true
# - path: etcd
#   waitReadiness: true
# - git:
#     url: git@gitlab.com:volterra/ves.io/cicd-deployment
#     ref: testglue
#     subDir: argo/k8s/argo-cd
