
# https://github.com/bitnami/charts/tree/master/bitnami/metallb
# 

namespace: metallb

resources:
#PREV: - github.com/metallb/metallb//manifests?ref=v0.11.0
- github.com/metallb/metallb/config/native?ref=v0.13.9
- config/pool.yaml

# DEPRE$CATED since 0.13.x
# configMapGenerator:
# - name: config
#   files:
#     - config=config/apealive.yaml

generatorOptions:
  disableNameSuffixHash: true
  #labels:
  #annotations:
# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
