image:
  repository: octoprint/octoprint
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 80
 
securityContext:
  # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
  privileged: true



enableServiceLinks: false
env:
  TZ: "Europe/Prague"
  ENABLE_MJPG_STREAMER: "false"
  MJPG_STREAMER_INPUT:  # "-y -n -r 640x480"
  CAMERA_DEV:  # /dev/video0
  OCTOPRINT_PORT: "5000"
persistence:
  data:
    enabled: true
    mountPath: /octoprint
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 6Gi  # 3G, but for larger prints, octoleaps require space for snaphosts
  printer:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyACM0

ingress:
   main:
     enabled: true
     ingressClassName: "traefik"
     annotations:
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
       traefik.ingress.kubernetes.io/router.tls: "true"
       hajimari.io/enable: "true"
       hajimari.io/icon: printer
       hajimari.io/group: home
       hajimari.io/appName: octoprint
     hosts:
     - host: octoprint.apealive.net
       paths:
       - path: /
         pathType: Prefix
     tls:
     - hosts:
       - octoprint.apealive.net

# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
