# https://github.com/minio/minio/tree/master/helm/minio

namespace: sys

commonLabels:
  feature: backup

generatorOptions:
  disableNameSuffixHash: true


resources:
- helm-rendered.yaml
- ./secret/root-credentials.yaml

patchesJson6902:
- target:
    version: .*
    kind: (StatefulSet|Deployment)
    name: .*
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        kubernetes.io/hostname: cmp1-nuc11

# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
