
namespace: iot

resources:
- helm-rendered.yaml
- ./overlays/ingressRoute-esphome.yaml

images:
- name: esphome/esphome
  newTag: stable

# NODE SELECTORS
patchesJson6902:
- target:
    version: .*
    kind: (StatefulSet|Deployment)
    name: .*
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        type: main
 
# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
