resources:
- helm-rendered.yaml
- ./secret/gitea-app-ini-database.yaml
- ./secret/gitea-admin.yaml
- ./overlays/ingress-traefik.yaml

patchesJson6902:
#- target:
#    version: .*
#    kind: StatefulSet
#    name: gitea
#  patch: |-
#    - op: remove
#      path: /spec/template/spec/initContainers/0/env/2/value
- target:
    version: .*
    kind: (StatefulSet|Deployment)
    name: gitea.*
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        type: main

# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
