deployments:
  - path: .
    vars:
    # CLUSTER SPECIFIC
      - file: context-{{ global.clusterName }}.yml
        ignoreMissing: true                        
        noOverride: true
    # BEST PRACTICE SETUP
    # ( unlike the other apps - for BJWs Helm lib the defaults is in helm values under common: )
      # - file: context.yml
      #   ignoreMissing: true                        
      #   noOverride: true
      # # cluster specific
