namespace: &ns media
               # if { namespace}  is used ^^ looks like clash here <class 'jinja2.utils.Namespace'>/Ingress/jellyfin: failed to patch <class 'jinja2.utils.Namespace'>/Ingress/jellyfin: namespaces "<class 'jinja2.utils.Namespace'>" not found

commonLabels:
  app: jellyfin
  #tag0: { deploy.tag0 }
  #dir1: { deploy.dir1 }

resources:
- helm-rendered.yaml
#- overlays/chromecast-fix-svc.yaml
#- overlays/ingressRoute.yaml

#patches:
#- path: overlays/chromecast-fix.yaml
#- target:
#    kind: Ingress
#    version: v1
#    name: .*
#  patch: |-
#    - op: replace
#      path: /spec/rules/0/http/paths/1/backend/service
#      value: { name: jellyfin-chromecast-fix, port: { number: 8088 }}

# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
