# vim: textwidth=120 nowrap ft=helm.jinja:syntax=on
# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/

deployments:
  - git:
      url: https://gitea.example.net/epcim/gitops-library.git
      subDir: service/kluctl
    passVars: true
    args: {{ args }}

  - path: ./kluctl
    when: args.manual



