# https://kluctl.io/docs/kluctl/reference/deployments/deployment-yml/
---
deployments:
# default services
{% for s in params.keys() %}
  - path: ../../service/{{ s }}
    #onlyRender: true
{% endfor %}

# tailored per-cluster deployments
#
# EXAMPLE/TEST
  # problem1: (better to link once for all from root deployment.yml)
  # - path: ../../service/jellyfin -> ./build/0/service/jellyfin-1 ??
  #   onlyRender: true
  - path: media-test/jellyfin-test
    vars:
    - values:
        compose: ../../../../compose
        service: ../../../../service
        namespace: whatever

